computed = [  ]
name = "paved::systems::account::account"
reads = [  ]
writes = [ "Game", "Builder", "Player", "Tile", "TilePosition", "Character", "CharacterPosition", "Tournament" ]
init_calldata = []
