[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x62ab43333e9c3f373fdbf5792a805314630eed0ce03f010d0895edb97dd6a13"
transaction_hash = "0x6932b1e893c35663c8f40c7cd712608883b059b96c9ad7f1671da5030ad834f"
block_number = 3
seed = "v3"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x21eb0302f882afaf157664fabf156d7e086d85f3eebfbc8301523e711b83d1c"
class_hash = "0x50717829d7dbd215bfd815a0fbbf950d2daf5b960e49e12753fc897fd84dc75"
original_class_hash = "0x50717829d7dbd215bfd815a0fbbf950d2daf5b960e49e12753fc897fd84dc75"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/paved_systems_host_host.json"
reads = []
writes = []
computed = []
name = "paved::systems::host::host"

[[contracts]]
kind = "DojoContract"
address = "0xecca957d70585d77de04c4e7086a5f5a86180749d3a25c2298301998326cb7"
class_hash = "0x3e673f059f703ed4aef23d373dc10360c9ad0cfb0b6371a1d9893674206330a"
original_class_hash = "0x3e673f059f703ed4aef23d373dc10360c9ad0cfb0b6371a1d9893674206330a"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/paved_systems_manage_manage.json"
reads = []
writes = []
computed = []
name = "paved::systems::manage::manage"

[[contracts]]
kind = "DojoContract"
address = "0x451e4008c32d27ad52775dc9c974544c01bd91a1fcc470f911de82da449042f"
class_hash = "0x4031044cc944573a489e298c094e5b299bf5163a9a60e48cb44fe4111952d90"
original_class_hash = "0x4031044cc944573a489e298c094e5b299bf5163a9a60e48cb44fe4111952d90"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/paved_systems_play_play.json"
reads = []
writes = []
computed = []
name = "paved::systems::play::play"

[[models]]
kind = "DojoModel"
class_hash = "0x4bba0836f34c2f613721e51293acfa04cb0db9c4b4ce4aa7e25c5cf29548daa"
original_class_hash = "0x4bba0836f34c2f613721e51293acfa04cb0db9c4b4ce4aa7e25c5cf29548daa"
abi = "abis/deployments/models/paved_models_builder_builder.json"
name = "paved::models::builder::builder"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models.members]]
name = "characters"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4fcacc0ee6d3043635277a46e5dfa25f0c259c78bf75270d4e67f7683788169"
original_class_hash = "0x4fcacc0ee6d3043635277a46e5dfa25f0c259c78bf75270d4e67f7683788169"
abi = "abis/deployments/models/paved_models_character_character.json"
name = "paved::models::character::character"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "index"
type = "u8"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models.members]]
name = "spot"
type = "u8"
key = false

[[models.members]]
name = "weight"
type = "u8"
key = false

[[models.members]]
name = "power"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7062c2bcdc48d60aa4a8b039a57ed4b668e24a6685282ee34ceeb913d6a8560"
original_class_hash = "0x7062c2bcdc48d60aa4a8b039a57ed4b668e24a6685282ee34ceeb913d6a8560"
abi = "abis/deployments/models/paved_models_character_character_position.json"
name = "paved::models::character::character_position"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = true

[[models.members]]
name = "spot"
type = "u8"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "index"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x54173378834f3dea20987963bfb726d699c47a318bcc21c13a02f62e8aeba64"
original_class_hash = "0x54173378834f3dea20987963bfb726d699c47a318bcc21c13a02f62e8aeba64"
abi = "abis/deployments/models/paved_models_game_game.json"
name = "paved::models::game::game"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "tiles"
type = "u128"
key = false

[[models.members]]
name = "tile_count"
type = "u32"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28f8338bb79847902c80c9cda94191276986868452e8cb47c5ca7af0ecb99b"
original_class_hash = "0x28f8338bb79847902c80c9cda94191276986868452e8cb47c5ca7af0ecb99b"
abi = "abis/deployments/models/paved_models_player_player.json"
name = "paved::models::player::player"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "paved"
type = "u32"
key = false

[[models.members]]
name = "master"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1c31bf9bf19f9438ac1d2f77817e6788878b9ed89d89440ca3637f91838d9ed"
original_class_hash = "0x1c31bf9bf19f9438ac1d2f77817e6788878b9ed89d89440ca3637f91838d9ed"
abi = "abis/deployments/models/paved_models_tile_tile.json"
name = "paved::models::tile::tile"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "plan"
type = "u8"
key = false

[[models.members]]
name = "orientation"
type = "u8"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "occupied_spot"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7b911b42fbf87955c5bcc226d2741bc371756ec1d2e06ef1c52ad127a4f1bda"
original_class_hash = "0x7b911b42fbf87955c5bcc226d2741bc371756ec1d2e06ef1c52ad127a4f1bda"
abi = "abis/deployments/models/paved_models_tile_tile_position.json"
name = "paved::models::tile::tile_position"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5b26b4c1d75f87f36f15a3ae911c47bf0340b62afde35e7c2ceb9ce637106d2"
original_class_hash = "0x5b26b4c1d75f87f36f15a3ae911c47bf0340b62afde35e7c2ceb9ce637106d2"
abi = "abis/deployments/models/paved_models_tournament_tournament.json"
name = "paved::models::tournament::tournament"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "prize"
type = "felt252"
key = false

[[models.members]]
name = "top1_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top2_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top3_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top1_score"
type = "u32"
key = false

[[models.members]]
name = "top2_score"
type = "u32"
key = false

[[models.members]]
name = "top3_score"
type = "u32"
key = false

[[models.members]]
name = "top1_claimed"
type = "bool"
key = false

[[models.members]]
name = "top2_claimed"
type = "bool"
key = false

[[models.members]]
name = "top3_claimed"
type = "bool"
key = false
