computed = [  ]
name = "paved::systems::daily::daily"
reads = [  ]
writes = [ "Game", "Builder", "Player", "Tile", "TilePosition", "Character", "CharacterPosition", "Tournament" ]
init_calldata = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]
