kind = "DojoModel"
class_hash = "0x6d656d9758d04dd45de9bfdb839d88f85a6ee61f983f2a147abfbb5892e5bb7"
original_class_hash = "0x6d656d9758d04dd45de9bfdb839d88f85a6ee61f983f2a147abfbb5892e5bb7"
abi = "manifests/sepolia/abis/base/models/paved_models_index_player.json"
name = "paved::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "master"
type = "felt252"
key = false
