kind = "DojoModel"
class_hash = "0x7b2d2c81df5a6a2000cdb7634d9a4fe4e973bcb50816f53f6456eac6a883c07"
name = "paved::models::player::player_name"

[[members]]
name = "name"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = false
