kind = "DojoModel"
class_hash = "0x1c31bf9bf19f9438ac1d2f77817e6788878b9ed89d89440ca3637f91838d9ed"
name = "paved::models::tile::tile"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = false

[[members]]
name = "plan"
type = "u8"
key = false

[[members]]
name = "orientation"
type = "u8"
key = false

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "occupied_spot"
type = "u8"
key = false
