[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/sepolia/abis/deployments/dojo_world_world.json"
address = "0x1f2ef7f19611458fac12624483eef613d1ad2660e8aea5969a678ddc25df0c2"
transaction_hash = "0x28d9795d592f117730a22fd628e226ce94683e8d572669a0f68e0878198e22f"
seed = "paved-v10"
name = "dojo::world::world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0xb625f70cb5e562d33938cbb251b97c3758aad52f74b13bf9faec2861dae984"
class_hash = "0x3efb67bdd2f204e6202dae32fdfd7cf42e1373747eaf595d4ff6e10341625d6"
original_class_hash = "0x3efb67bdd2f204e6202dae32fdfd7cf42e1373747eaf595d4ff6e10341625d6"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/sepolia/abis/deployments/contracts/paved_systems_account_account.json"
reads = []
writes = [
    "Game",
    "Builder",
    "Player",
    "Tile",
    "TilePosition",
    "Character",
    "CharacterPosition",
    "Tournament",
]
computed = []
init_calldata = []
name = "paved::systems::account::account"

[[contracts]]
kind = "DojoContract"
address = "0x3b470d8557918ad70a30f65baef814d322ab288813fb448c81a72f1efa7cbe4"
class_hash = "0x3324295eca593cc31d97770523b9be5059736af54ca4eda08b9a8fa4aeccc86"
original_class_hash = "0x3324295eca593cc31d97770523b9be5059736af54ca4eda08b9a8fa4aeccc86"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/sepolia/abis/deployments/contracts/paved_systems_daily_daily.json"
reads = []
writes = [
    "Game",
    "Builder",
    "Player",
    "Tile",
    "TilePosition",
    "Character",
    "CharacterPosition",
    "Tournament",
]
computed = []
init_calldata = ["0x044e6bcc627e6201ce09f781d1aae44ea4c21c2fdef299e34fce55bef2d02210"]
name = "paved::systems::daily::daily"

[[models]]
kind = "DojoModel"
class_hash = "0x4d82dbbe7fee8760ff082d5c0db9c76297c68b5a377d26f83510eec73a2cf3d"
original_class_hash = "0x4d82dbbe7fee8760ff082d5c0db9c76297c68b5a377d26f83510eec73a2cf3d"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_builder.json"
name = "paved::models::index::builder"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models.members]]
name = "characters"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xaf036472f4a4716de4e3a159f2903425a949357ec091a0d9496522f1c829ff"
original_class_hash = "0xaf036472f4a4716de4e3a159f2903425a949357ec091a0d9496522f1c829ff"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_character.json"
name = "paved::models::index::character"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "index"
type = "u8"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models.members]]
name = "spot"
type = "u8"
key = false

[[models.members]]
name = "weight"
type = "u8"
key = false

[[models.members]]
name = "power"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x710d20b596f1b1666cb717ffe3cf50db3f0f64640fb0417113cf9c983905fe4"
original_class_hash = "0x710d20b596f1b1666cb717ffe3cf50db3f0f64640fb0417113cf9c983905fe4"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_character_position.json"
name = "paved::models::index::character_position"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = true

[[models.members]]
name = "spot"
type = "u8"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "index"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3c0fb77988190fac9807592f54b3d956457fa1af9e66f3257885c39a4946aa4"
original_class_hash = "0x3c0fb77988190fac9807592f54b3d956457fa1af9e66f3257885c39a4946aa4"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_game.json"
name = "paved::models::index::game"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "discarded"
type = "u8"
key = false

[[models.members]]
name = "built"
type = "u8"
key = false

[[models.members]]
name = "tiles"
type = "u128"
key = false

[[models.members]]
name = "tile_count"
type = "u32"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false

[[models.members]]
name = "end_time"
type = "u64"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "mode"
type = "u8"
key = false

[[models.members]]
name = "tournament_id"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6d656d9758d04dd45de9bfdb839d88f85a6ee61f983f2a147abfbb5892e5bb7"
original_class_hash = "0x6d656d9758d04dd45de9bfdb839d88f85a6ee61f983f2a147abfbb5892e5bb7"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_player.json"
name = "paved::models::index::player"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "master"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x18fac425cbb97c5e605b3c41ea226c4c0bdf3029234f565e681792ca2df2c01"
original_class_hash = "0x18fac425cbb97c5e605b3c41ea226c4c0bdf3029234f565e681792ca2df2c01"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_tile.json"
name = "paved::models::index::tile"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "plan"
type = "u8"
key = false

[[models.members]]
name = "orientation"
type = "u8"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "occupied_spot"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5901857908756661373045d3a1d8c9a13ca366cf50310b4025d21143b4bb29"
original_class_hash = "0x5901857908756661373045d3a1d8c9a13ca366cf50310b4025d21143b4bb29"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_tile_position.json"
name = "paved::models::index::tile_position"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6f212e189ebf03a128ad905ed2e8af085eaa58ba32faed7c26d242e561a93f"
original_class_hash = "0x6f212e189ebf03a128ad905ed2e8af085eaa58ba32faed7c26d242e561a93f"
abi = "manifests/sepolia/abis/deployments/models/paved_models_index_tournament.json"
name = "paved::models::index::tournament"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "prize"
type = "felt252"
key = false

[[models.members]]
name = "top1_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top2_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top3_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top1_score"
type = "u32"
key = false

[[models.members]]
name = "top2_score"
type = "u32"
key = false

[[models.members]]
name = "top3_score"
type = "u32"
key = false

[[models.members]]
name = "top1_claimed"
type = "bool"
key = false

[[models.members]]
name = "top2_claimed"
type = "bool"
key = false

[[models.members]]
name = "top3_claimed"
type = "bool"
key = false
