kind = "DojoModel"
class_hash = "0x6e4e84f7676611e3e99f521b6d91252566233f5920eca45e1aa4d76f2ae8fe5"
original_class_hash = "0x6e4e84f7676611e3e99f521b6d91252566233f5920eca45e1aa4d76f2ae8fe5"
abi = "manifests/dev/abis/base/models/paved_models_team_team.json"
name = "paved::models::team::team"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "order"
type = "u8"
key = true

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "alliance"
type = "u8"
key = false
