kind = "DojoModel"
class_hash = "0xb39f4d5ca29ba4f42bb3c942f3075a941174fcc41596d54ff0724f75550f17"
original_class_hash = "0xb39f4d5ca29ba4f42bb3c942f3075a941174fcc41596d54ff0724f75550f17"
abi = "manifests/dev/base/abis/models/paved-Game-18a55e57.json"
tag = "paved-Game"
qualified_path = "paved::models::index::game"
manifest_name = "paved-Game-18a55e57"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "discarded"
type = "u8"
key = false

[[members]]
name = "built"
type = "u8"
key = false

[[members]]
name = "tiles"
type = "u128"
key = false

[[members]]
name = "tile_count"
type = "u32"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "end_time"
type = "u64"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "mode"
type = "u8"
key = false

[[members]]
name = "tournament_id"
type = "u64"
key = false
