kind = "DojoModel"
class_hash = "0xb2bd4519986971b4ca124641887e7c6d2121622c52fa86dca224b19e327cd5"
original_class_hash = "0xb2bd4519986971b4ca124641887e7c6d2121622c52fa86dca224b19e327cd5"
abi = "manifests/dev/abis/base/models/paved_models_index_game.json"
name = "paved::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "tiles"
type = "u128"
key = false

[[members]]
name = "tile_count"
type = "u32"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "mode"
type = "u8"
key = false
