kind = "DojoModel"
class_hash = "0x67c98cf758f1df4ef6bd5c7e9e92c4891ce792050aea89e3169f864f7d857c2"
original_class_hash = "0x67c98cf758f1df4ef6bd5c7e9e92c4891ce792050aea89e3169f864f7d857c2"
abi = "manifests/dev/abis/base/models/paved_models_player_player.json"
name = "paved::models::player::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "order"
type = "u8"
key = false

[[members]]
name = "bank"
type = "u8"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "paved"
type = "u32"
key = false

[[members]]
name = "master"
type = "felt252"
key = false
