kind = "DojoModel"
class_hash = "0x88fa6e2c0ecc777bdd58aebaa29b4419c0688cef808e079d9b35928444dba7"
original_class_hash = "0x88fa6e2c0ecc777bdd58aebaa29b4419c0688cef808e079d9b35928444dba7"
abi = "manifests/dev/abis/base/models/paved_models_builder_builder.json"
name = "paved::models::builder::builder"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "index"
type = "u32"
key = false

[[members]]
name = "order"
type = "u8"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "tile_id"
type = "u32"
key = false

[[members]]
name = "characters"
type = "u8"
key = false

[[members]]
name = "claimed"
type = "felt252"
key = false
