kind = "DojoModel"
class_hash = "0x430429636b12af5aaa2d624df84c66223c316a73b944e9807bb64c6ed6d367c"
original_class_hash = "0x430429636b12af5aaa2d624df84c66223c316a73b944e9807bb64c6ed6d367c"
abi = "manifests/dev/abis/base/models/paved_models_builder_builder.json"
name = "paved::models::builder::builder"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = false

[[members]]
name = "characters"
type = "u8"
key = false
