kind = "DojoModel"
class_hash = "0x53863c095b9fc1c86ef1ae6309adc4a5e03929780ddbd2db73472aec8e717cb"
original_class_hash = "0x53863c095b9fc1c86ef1ae6309adc4a5e03929780ddbd2db73472aec8e717cb"
abi = "manifests/dev/abis/base/models/paved_models_player_player.json"
name = "paved::models::player::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "paved"
type = "u32"
key = false

[[members]]
name = "master"
type = "felt252"
key = false
