kind = "DojoModel"
class_hash = "0x16b6b7656733e27ef230ce67268c38680f1886d8cc6e7c1f2142004d6d9b60c"
original_class_hash = "0x16b6b7656733e27ef230ce67268c38680f1886d8cc6e7c1f2142004d6d9b60c"
abi = "manifests/dev/abis/base/models/paved_models_tile_tile_position.json"
name = "paved::models::tile::tile_position"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = false
