kind = "DojoModel"
class_hash = "0x18fac425cbb97c5e605b3c41ea226c4c0bdf3029234f565e681792ca2df2c01"
original_class_hash = "0x18fac425cbb97c5e605b3c41ea226c4c0bdf3029234f565e681792ca2df2c01"
abi = "manifests/starknet/abis/base/models/paved_models_index_tile.json"
name = "paved::models::index::tile"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = false

[[members]]
name = "plan"
type = "u8"
key = false

[[members]]
name = "orientation"
type = "u8"
key = false

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "occupied_spot"
type = "u8"
key = false
