kind = "DojoModel"
class_hash = "0x17e45c9c4cd654c8b424ec087eb6d09953f6a7ad2a7737e54e17e0896e05786"
original_class_hash = "0x17e45c9c4cd654c8b424ec087eb6d09953f6a7ad2a7737e54e17e0896e05786"
abi = "manifests/starknet/abis/base/models/paved_models_index_player.json"
name = "paved::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "paved"
type = "u32"
key = false

[[members]]
name = "master"
type = "felt252"
key = false
