[package]
name = "paved"
version = "0.0.0"
cairo-version = "=2.7.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo --profile dev clean && sozo --profile dev build && sozo --profile dev migrate plan && sozo --profile dev migrate apply"

[dependencies]
origami_random = { git = "https://github.com/dojoengine/origami", tag = "v1.0.0-alpha.8" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.8" }

[[target.dojo]]

[profile.sepolia]
