kind = "DojoContract"
class_hash = "0x78b559b3a1cc4905b2243f2ffcc488ad3329f2f7fb2bebf239031c07cd2b989"
original_class_hash = "0x78b559b3a1cc4905b2243f2ffcc488ad3329f2f7fb2bebf239031c07cd2b989"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/paved_systems_weekly_weekly.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::weekly::weekly"
