kind = "DojoContract"
class_hash = "0x3dfabb4a3088087a742119cc73f721f93359771fea191142896c0c066c6e333"
original_class_hash = "0x3dfabb4a3088087a742119cc73f721f93359771fea191142896c0c066c6e333"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/paved_systems_account_account.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::account::account"
