computed = []
name = "paved::systems::tutorial::tutorial"
reads = []
writes = [
    "Game",
    "Builder",
    "Player",
    "Tile",
    "TilePosition",
    "Character",
    "CharacterPosition",
]
init_calldata = []
