kind = "DojoContract"
class_hash = "0x6c07d56a81b940ef6333b0fb1bc423e626c8da8e9d9431a56b54b842e8a3357"
original_class_hash = "0x6c07d56a81b940ef6333b0fb1bc423e626c8da8e9d9431a56b54b842e8a3357"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/paved-Account-32528a5a.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Account"
systems = ["create"]
manifest_name = "paved-Account-32528a5a"
