kind = "DojoContract"
class_hash = "0x517c968ffa1095e9ee8c7301adef795b10883bda0f0462a3699f5be21136ac1"
original_class_hash = "0x517c968ffa1095e9ee8c7301adef795b10883bda0f0462a3699f5be21136ac1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_daily_daily.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::daily::daily"
