kind = "DojoContract"
class_hash = "0x75eaa5133907bc43549d01a442b3f365aaa9fcd73a22e5afed10cc62115fd43"
original_class_hash = "0x75eaa5133907bc43549d01a442b3f365aaa9fcd73a22e5afed10cc62115fd43"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_weekly_weekly.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::weekly::weekly"
