kind = "DojoContract"
class_hash = "0x2c854a42fc63f0844a83aa7b786802ec6783740cc08f30bb7b9b01821110851"
original_class_hash = "0x2c854a42fc63f0844a83aa7b786802ec6783740cc08f30bb7b9b01821110851"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_tutorial_tutoriable.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::tutorial::tutoriable"
