kind = "DojoContract"
class_hash = "0x1e43c58f80c47c78d7a4e4bf79902bca2cb6bf7c0ed4b5ccb245297d8b98186"
original_class_hash = "0x1e43c58f80c47c78d7a4e4bf79902bca2cb6bf7c0ed4b5ccb245297d8b98186"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-Tutorial-242a6cba.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Tutorial"
systems = [
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Tutorial-242a6cba"
