kind = "DojoContract"
class_hash = "0x3dd73cb11d304a91d88e1afb237804e19583863afe531b3c65377e092310e10"
original_class_hash = "0x3dd73cb11d304a91d88e1afb237804e19583863afe531b3c65377e092310e10"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-tutorial-259085b2.json"
reads = []
writes = []
init_calldata = []
tag = "paved-tutorial"
systems = [
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-tutorial-259085b2"
