kind = "DojoContract"
class_hash = "0x73870689d74e27327d0358e907e0517634e88ae34ad9ecdb64c243e817ab65a"
original_class_hash = "0x73870689d74e27327d0358e907e0517634e88ae34ad9ecdb64c243e817ab65a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_daily_daily.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::daily::daily"
