kind = "DojoContract"
class_hash = "0x2967d666689f013c52e9e9a21d84243eab36c2c7ed03330bf6d776af8f4c326"
original_class_hash = "0x2967d666689f013c52e9e9a21d84243eab36c2c7ed03330bf6d776af8f4c326"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-Daily-190dcfe2.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Daily"
systems = [
    "claim",
    "sponsor",
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Daily-190dcfe2"
