kind = "DojoContract"
class_hash = "0x64cae238bd3563c743c75f857c9db8a453601f74343e9a94fe05d50afc93dac"
original_class_hash = "0x64cae238bd3563c743c75f857c9db8a453601f74343e9a94fe05d50afc93dac"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_daily_daily.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::daily::daily"
