kind = "DojoContract"
class_hash = "0x1bdcdebd271e57b092a106a74038dc1a88412eee4825d3d592593fc1c8556f"
original_class_hash = "0x1bdcdebd271e57b092a106a74038dc1a88412eee4825d3d592593fc1c8556f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-token-5d8a7360.json"
reads = []
writes = []
init_calldata = []
tag = "paved-token"
systems = []
manifest_name = "paved-token-5d8a7360"
