kind = "DojoContract"
class_hash = "0x6135b62b589b20211d88a7eb70bf05c29d6ef8a9526fbbe0e9f91608dadfef3"
original_class_hash = "0x6135b62b589b20211d88a7eb70bf05c29d6ef8a9526fbbe0e9f91608dadfef3"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_account_account.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "paved::systems::account::account"
