kind = "DojoContract"
class_hash = "0x2f3b980a60c4eea7865908e68a533e32f84e79c3e18daf21ea082f7a0286666"
original_class_hash = "0x2f3b980a60c4eea7865908e68a533e32f84e79c3e18daf21ea082f7a0286666"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_host_host.json"
reads = []
writes = []
computed = []
name = "paved::systems::host::host"
