kind = "DojoContract"
class_hash = "0x58cd90ba5402ff83faf0c6d8f25c0d137473e0524449d152e3397b5a1b5f8af"
original_class_hash = "0x58cd90ba5402ff83faf0c6d8f25c0d137473e0524449d152e3397b5a1b5f8af"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-daily-1f922ba9.json"
reads = []
writes = []
init_calldata = []
tag = "paved-daily"
systems = [
    "claim",
    "sponsor",
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-daily-1f922ba9"
